apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falcosidekick.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "falcosidekick.name" . }}
    helm.sh/chart: {{ include "falcosidekick.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.config.slack.webhookurl }}
  slack-webhookurl: "{{ .Values.config.slack.webhookurl | b64enc }}"
  {{- end }}
  {{- if .Values.config.datadog.apikey }}
  datadog-apikey: "{{ .Values.config.datadog.apikey | b64enc }}"
  {{- end }}
  {{- if .Values.config.alertmanager.hostport }}
  alertmanager-hostport: "{{ .Values.config.alertmanager.hostport | b64enc }}"
  {{- end }}
  {{- if .Values.config.elasticsearch.hostport }}
  elasticsearch-hostport: "{{ .Values.config.elasticsearch.hostport | b64enc }}"
  {{- end }}
  {{- if .Values.config.influxdb.hostport }}
  influxdb-hostport: "{{ .Values.config.influxdb.hostport | b64enc }}"
  {{- end }}
  {{- if and .Values.config.influxdb.user .Values.config.influxdb.password }}
  influxdb-user: "{{ .Values.config.influxdb.user | b64enc }}"
  influxdb-password: "{{ .Values.config.influxdb.password | b64enc }}"
  {{- end }}
